# Generated by Django 4.0.2 on 2022-03-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customer_order_customerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='CustomerId',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
